---
- name: Test Windows SSH ansible_connection
  hosts: windows
  gather_facts: true

  tasks:
    - name: Test connection with ping
      ansible.builtin.win_ping:

    - name: Display succes message
      ansible.builtin.debug:
        msg: "Succesfully connected to {{ inventory_hostname }} via SSH"
  
    - name: Run Powershell command via SSH
      ansible.windows.win_shell: |
        $PSVersionTable.PSVersion | Select-Object Major, Minor, Build
      register: ps_version

    - name: Display Powershell ps_version
      ansible.builtin.debug:
        msg: "{{ ps_version.stdout_lines }}"